version: "3"

services:
  backend:
    restart: always
    build: .
    env_file: ./instance/.env
    volumes:
      - .:/app
    depends_on:
    - database
    links:
      - "database:localhost"
    ports:
      - "5000:5000"

  database:
    restart: always
    image: postgres:latest
    env_file: ./instance/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
